sudo: required
language: cpp
os:
  - linux
compiler:
  - gcc
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - cmake

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8 -std=c++14 -DENABLE_REINFORCEMENT_LEARNING" CC="gcc-4.8"; fi

before_install:
  - sudo apt-get install libssl-dev
  - sudo apt-get install libjansson-dev
  - sh scripts/install-libprogbase.sh
  - sh scripts/install-libprogbase-cpp.sh

script:
  - cmake .
  - make