sudo: required
language: cpp
os:
  - linux

  matrix:
    include:
      - env: CXX=g++-5 CC=gcc-5
        addons:
          apt:
            packages:
              - g++-5
            sources: &sources
              - ubuntu-toolchain-r-test
              - llvm-toolchain-precise
              - llvm-toolchain-precise-3.7
              - llvm-toolchain-precise-3.6
      - env: CXX=g++-4.9 CC=gcc-4.9
        addons:
          apt:
            packages:
              - g++-4.9
            sources: *sources
compiler:
  - gcc
  - g++
  - clang++
before_install:
  - sudo apt-get install libssl-dev
  - sudo apt-get install libjansson-dev
  - sh scripts/install-libprogbase.sh
  - sh scripts/install-libprogbase-cpp.sh

script:
  - cmake .
  - make