sudo: false
language: cpp
os:
  - linux
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
compiler:
  - gcc
  - g++
  - clang++
before_install:
  - sudo apt-get install libssl-dev
  - sudo apt-get install libjansson-dev
  - sh scripts/install-libprogbase.sh
  - sh scripts/install-libprogbase-cpp.sh

script:
  - cmake .
  - make