{
  "language": "cpp",
  "compiler": "g++",
  "before_install": [
    "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test",
    "sudo apt-get update -qq",
    "sudo apt-get install libssl-dev",
    "sudo apt-get install libjansson-dev",
    "sh scripts/install-libprogbase.sh",
    "sh scripts/install-libprogbase-cpp.sh"
  ],
  "install": [
    "sudo apt-get install -qq g++-4.8",
    "export CXX=\"g++-4.8\""
  ],
  "script": [
    "cmake .",
    "make ."
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
